function(culprit_group_folders)
    if(MSVC_IDE)
        # === Group source files in src/
        file(GLOB_RECURSE SRC_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/src/*)
        foreach(file IN LISTS SRC_FILES)
            get_filename_component(dir "${file}" PATH)
            string(REPLACE "/" "\\" group "${dir}")
            string(REPLACE "src" "Sources" group "${group}")
            source_group("${group}" FILES "${CMAKE_CURRENT_SOURCE_DIR}/${file}")
        endforeach()

        # === Group headers in include/
        if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/include")
            file(GLOB_RECURSE INCLUDE_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/include/*)
            foreach(file IN LISTS INCLUDE_FILES)
                get_filename_component(dir "${file}" PATH)
                string(REPLACE "/" "\\" group "${dir}")
                string(REPLACE "include" "Include" group "${group}")
                source_group("${group}" FILES "${CMAKE_CURRENT_SOURCE_DIR}/${file}")
            endforeach()
        endif()

        # === Group headers in public/
        if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/public")
            file(GLOB_RECURSE PUBLIC_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/public/*)
            foreach(file IN LISTS PUBLIC_FILES)
                get_filename_component(dir "${file}" PATH)
                string(REPLACE "/" "\\" group "${dir}")
                string(REPLACE "public" "Public" group "${group}")
                source_group("${group}" FILES "${CMAKE_CURRENT_SOURCE_DIR}/${file}")
            endforeach()
        endif()
    endif()
endfunction()